### ISSUE TITLE
1.20.4 and 1.20.5 panic 

### ISSUE THREAD

**Issue by kr521** [coroot/coroot-node-agent#110]
I0716 08:57:14.249790  876706 registry.go:241] TCP connection from unknown container {connection-open none 2233641 10.2.32.72:44268 10.75.14.29:13929 10 30578953183824468 1.535224ms <nil>}
E0716 08:57:21.943885  876706 tls.go:92] pid=877518 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:21.943885  876706 tls.go:92] pid=877518 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:21.943885  876706 tls.go:92] pid=877518 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:21.943885  876706 tls.go:92] pid=877518 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:23.759816  876706 tls.go:92] pid=877427 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:23.759816  876706 tls.go:92] pid=877427 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:23.759816  876706 tls.go:92] pid=877427 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:23.759816  876706 tls.go:92] pid=877427 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:24.366765  876706 tls.go:92] pid=877367 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:24.366765  876706 tls.go:92] pid=877367 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:24.366765  876706 tls.go:92] pid=877367 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
E0716 08:57:24.366765  876706 tls.go:92] pid=877367 libssl_version=v1.0.0: failed to attach uprobe: symbol SSL_write_ex: not found
panic: runtime error: index out of range [0] with length 0

goroutine 23986 [running]:
github.com/coroot/coroot-node-agent/containers.(*Process).instrumentPython(0xc0031fa000, 0x10?)
	/tmp/src/containers/process.go:92 +0x2af
github.com/coroot/coroot-node-agent/containers.(*Process).instrument(0xc0031fa000, 0xc002311798?)
	/tmp/src/containers/process.go:69 +0x134
created by github.com/coroot/coroot-node-agent/containers.NewProcess in goroutine 163
	/tmp/src/containers/process.go:37 +0xfb

1.20.3 no have this issue.

**Comment by def** [comment]
@kr521 thanks for the report. I'm working on the fix

**Comment by def** [comment]
This is fixed in 1.20.6
