### ISSUE TITLE
No support for GKE?

### ISSUE THREAD

**Issue by chicagobuss** [coroot/coroot-node-agent#15]
Tried to install coroot on GKE - node-agents are all crashing with panics like this:
```
panic: interface conversion: bpf.MapValue is *lbmap.Backend4ValueV3, not *lbmap.Backend4Value

goroutine 101 [running]:
github.com/coroot/coroot-node-agent/containers.lookupCilium4({{{0xc000a51a78?, 0xc000216340?}, 0xc000122078?}, 0x1940?}, {{{0xb07965?, 0xc000216340?}, 0xc000122078?}, 0xd31b?})
        /tmp/src/containers/cilium.go:107 +0x4d8
github.com/coroot/coroot-node-agent/containers.lookupCiliumConntrackTable({{{0xc000216340?, 0xc000056000?}, 0xc000122078?}, 0x1970?}, {{{0xc000a519d0?, 0xbbbddc?}, 0xc000122078?}, 0x1?})
        /tmp/src/containers/cilium.go:66 +0x54
github.com/coroot/coroot-node-agent/containers.(*Container).getActualDestination(0xc0008ab9e0, 0x12fb, {{{0x0?, 0x1?}, 0xc000122078?}, 0x1b78?}, {{{0x0, 0xffff0a0c0001}, 0xc000122078}, 0x1bb})
        /tmp/src/containers/container.go:477 +0xa7
github.com/coroot/coroot-node-agent/containers.(*Container).onConnectionOpen(0xc0008ab9e0, 0x12fb, 0x8, {{{0x0?, 0x0?}, 0xc000122078?}, 0x0?}, {{{0x0, 0xffff0a0c0001}, 0xc000122078}, ...}, ...)
        /tmp/src/containers/container.go:451 +0x27b
github.com/coroot/coroot-node-agent/containers.(*Registry).handleEvents(0xc00047e040, 0xc0005233e0)
        /tmp/src/containers/registry.go:192 +0x3df
created by github.com/coroot/coroot-node-agent/containers.NewRegistry
        /tmp/src/containers/registry.go:89 +0x4db
```

**Comment by apetruhin** [comment]
@chicagobuss, we've reproduced this issue and are currently working on a fix.

**Comment by apetruhin** [comment]
@chicagobuss , thank you for the report. Please update coroot-node-agent to the latest version (1.8.1)

**Comment by chicagobuss** [comment]
ya it's working great now with the 1.8.1 image

Can I ask how your tool works with dataplanev2 when hubble doesn't?  how are they different?
